name: End to End Testing

on:
  # https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
  # pull_request_target is potentially dangerous target so we keep it strict
  # under the label and benefit from secret propagation
  pull_request_target:
    types:
      - synchronize
      - labeled

env:
  UP_API_TOKEN: ${{ secrets.UP_API_TOKEN }}
  UP_ORG: ${{ secrets.UP_ORG }}

jobs:
  e2e:
    if: contains(github.event.pull_request.labels.*.name, 'run-e2e-tests')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install and login with up
        if: env.UP_API_TOKEN != '' && env.UP_ORG != ''
        uses: upbound/action-up@v1
        with:
          api-token: ${{ secrets.UP_API_TOKEN }}
          organization: ${{ secrets.UP_ORG }}

      # doesn't work with plain token when pushing otherwise
      - name: Login to xpkg with robot
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: xpkg.upbound.io
          username: ${{ secrets.UP_ROBOT_ID }}
          password: ${{ secrets.UP_API_TOKEN }}

      - name: Build project
        run: up project build

      - name: Switch up context
        run: up ctx ${{ secrets.UP_ORG }}/upbound-gcp-us-central-1/${{ secrets.UP_GROUP }}

      - name: Download and install Upbound-enhanced Chainsaw(remove me later)
        run: |
          curl -L -o /usr/local/bin/chainsaw https://yurychainsaw.blob.core.windows.net/chainsaw/chainsaw
          chmod +x /usr/local/bin/chainsaw

      - name: Run e2e tests
        run: up test run tests/* --e2e
